<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-04-25 20:13

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('be_acl');
return array(
	'ux_SC_mod_web_perm_index' => $extensionPath . 'res/class.ux_sc_mod_web_perm_index.php',
	'tx_beacl_userauthgroup' => $extensionPath . 'res/class.tx_beacl_userauthgroup.php',
);
?>